import { images } from '../constants';

export const booksData = {
    onepiece: {
        id: 1,
        bookName: "One \n Piece",
        bookCover: images.onepiece,
        rating: "4.5/5",
        language: "Español",
        episodeNo: 100,
        author: "Jasmine Warga",
        genre: ["Romance", "Adventure", "Drama"],
        readed: "12k",
        description: "...",
        backgroundColor: "rgba(240,240,232,0.9)",
        navTintColor: "#000",
    },
    demonslayer: {
        id: 2,
        bookName: "Demon \n Slayer",
        bookCover: images.demonslayer,
        rating: "4.3/5",
        episodeNo: 289,
        genre: [
            "Adventure", "Drama"
        ],
        readed: "43k",
        description: "Demon Slayer: Kimetsu no Yaiba es una serie de manga japonesa escrita e ilustrada por Koyoharu Gotouge. Fue serializado en la revista de manga shōnen de Shueisha Weekly Shōnen Jump desde febrero de 2016 hasta mayo de 2020, con sus capítulos recopilados en 23 volúmenes de tankōbon."  
    },
    komisan: {
        id: 3,
        bookName: "Komi-san \n wa",
        bookCover: images.komisan,
        rating: "3.5/5",
        episodeNo: 383,
        genre: [
            "Drama", "Adventure", "Romance"
        ],
        readed: "83k",
        description: "Komi Can't Communicate es una serie de manga japonesa escrita e ilustrada por Tomohito Oda. Ha sido serializado en la revista de manga shōnen Weekly Shōnen Sunday de Shogakukan desde mayo de 2016, con sus capítulos recopilados en 29 volúmenes de tankōbon a partir de abril de 2023. La serie tiene licencia en Norteamérica por Viz Media",
        backgroundColor: "rgba(119,77,143,0.9)",
       
    },
    dragonballmultiverse: {
        id: 4,
        bookName: "Dragon ball \n Multiverse",
        bookCover: images.dragonballmultiverse,
        rating: "3.4/5",
        language: "Español",
        episodeNo: 75,
        readed: "13k",
        description: "Dragon Ball Multiverse (o DBM para abreviar) es una secuela hecha por fanáticos del Dragon Ball Manga y es un doujinshi en línea gratuito (cómic hecho por fanáticos en japonés).",
   
    },
    chainsawman: {
        id: 5,
        bookName: "Chain Saw\n Man",
        bookCover: images.chainsawman,
        rating: "3.2/5",
        language: "Español",
        episodeNo: 146,
        readed: "275k",
        description: "un joven empobrecido que hace un contrato que fusiona su cuerpo con el de un demonio parecido a un perro llamado Pochita, otorgándole la capacidad de transformar partes de su cuerpo en motosierras",
    },
    jibakushounen: {
        id: 6,
        bookName: "Jibaku \n Shounen",
        bookCover: images.jibakushounen,
        rating: "3.2/5",
        language: "Español",
        episodeNo: 146,
        readed: "275k",
        description: "un joven empobrecido que hace un contrato que fusiona su cuerpo con el de un demonio parecido a un perro llamado Pochita, otorgándole la capacidad de transformar partes de su cuerpo en motosierras",
    },
    bluelock: {
        id: 7,
        bookName: "Blue \n Lock",
        bookCover: images.bluelock,
        rating: "4.2/5",
        language: "Español",
        episodeNo: 146,
        readed: "25k",
        description: "un joven empobrecido que hace un contrato que fusiona su cuerpo con el de un demonio parecido a un perro llamado Pochita, otorgándole la capacidad de transformar partes de su cuerpo en motosierras",
    },
       bananafish: {
        id: 8,
        bookName: "Banana \n fish",
        bookCover: images.bananafish,
        rating: "3.2/5",
        language: "Español",
        episodeNo: 146,
        readed: "275k",
        description: "un joven empobrecido que hace un contrato que fusiona su cuerpo con el de un demonio parecido a un perro llamado Pochita, otorgándole la capacidad de transformar partes de su cuerpo en motosierras",
    },
    
        recordofragnarok: {
        id: 9,
        bookName: "Record of\n Ragnarok",
        bookCover: images.recordofragnarok,
        rating: "3.2/5",
        language: "Español",
        episodeNo: 146,
        readed: "275k",
        description: "un joven empobrecido que hace un contrato que fusiona su cuerpo con el de un demonio parecido a un perro llamado Pochita, otorgándole la capacidad de transformar partes de su cuerpo en motosierras",
    },
    
        goodnightpunpun: {
        id: 10,
        bookName: "Goodnight\n Punpun",
        bookCover: images.goodnightpunpun,
        rating: "3.2/5",
        language: "Español",
        episodeNo: 146,
        readed: "275k",
        description: "un joven empobrecido que hace un contrato que fusiona su cuerpo con el de un demonio parecido a un perro llamado Pochita, otorgándole la capacidad de transformar partes de su cuerpo en motosierras",
    },
        talesofdemonsandgods: {
        id: 11,
        bookName: "Tales of Demons\n and Gods",
        bookCover: images.talesofdemonsandgods,
        rating: "3.2/5",
        language: "Español",
        episodeNo: 146,
        readed: "275k",
        description: "un joven empobrecido que hace un contrato que fusiona su cuerpo con el de un demonio parecido a un perro llamado Pochita, otorgándole la capacidad de transformar partes de su cuerpo en motosierras",
    },
    jojosbizarreadventure: {
        id: 12,
        bookName: "JoJos Bizarre \n Adventure ",
        bookCover: images.jojosbizarreadventure,
        rating: "3.2/5",
        language: "Español",
        episodeNo: 146,
        readed: "275k",
        description: "un joven empobrecido que hace un contrato que fusiona su cuerpo con el de un demonio parecido a un perro llamado Pochita, otorgándole la capacidad de transformar partes de su cuerpo en motosierras",
    },
    spyxfamily: {
        id: 13,
        bookName: "Spy X \n Family",
        bookCover: images.spyxfamily,
        rating: "3.2/5",
        language: "Español",
        episodeNo: 146,
        readed: "275k",
        description: "un joven empobrecido que hace un contrato que fusiona su cuerpo con el de un demonio parecido a un perro llamado Pochita, otorgándole la capacidad de transformar partes de su cuerpo en motosierras",
    },
  
    Berserk: {
        id: 14,
        bookName: "Berserk",
        bookCover: images.Berserk,
        rating: "3.2/5",
        language: "Español",
        episodeNo: 146,
        readed: "275k",
        description: "un joven empobrecido que hace un contrato que fusiona su cuerpo con el de un demonio parecido a un perro llamado Pochita, otorgándole la capacidad de transformar partes de su cuerpo en motosierras",
    },
    
    blackclover: {
        id: 15,
        bookName: "Black\nclover",
        bookCover: images.blackclover,
        rating: "3.2/5",
        language: "Español",
        episodeNo: 146,
        readed: "275k",
        description: "un joven empobrecido que hace un contrato que fusiona su cuerpo con el de un demonio parecido a un perro llamado Pochita, otorgándole la capacidad de transformar partes de su cuerpo en motosierras",
    },
    ijiranaidenagatorosan: {
        id: 16,
        bookName: "Ijiranaide \n nagatorosan ",
        bookCover: images.ijiranaidenagatorosan,
        rating: "3.2/5",
        language: "Español",
        episodeNo: 146,
        readed: "275k",
        description: "un joven empobrecido que hace un contrato que fusiona su cuerpo con el de un demonio parecido a un perro llamado Pochita, otorgándole la capacidad de transformar partes de su cuerpo en motosierras",
    },
    pumpkinnight: {
        id: 17,
        bookName: "Pumpkin \n Night",
        bookCover: images.pumpkinnight,
        rating: "3.2/5",
        language: "Español",
        episodeNo: 146,
        readed: "275k",
        description: "un joven empobrecido que hace un contrato que fusiona su cuerpo con el de un demonio parecido a un perro llamado Pochita, otorgándole la capacidad de transformar partes de su cuerpo en motosierras",
    },
    Kaiju: {
        id: 18,
        bookName: "Kaiju",
        bookCover: images.Kaiju,
        rating: "3.2/5",
        language: "Español",
        episodeNo: 146,
        readed: "275k",
        description: "un joven empobrecido que hace un contrato que fusiona su cuerpo con el de un demonio parecido a un perro llamado Pochita, otorgándole la capacidad de transformar partes de su cuerpo en motosierras",
    },
    Mokushiroku: {
        id: 19,
        bookName: "Mokushiroku",
        bookCover: images.Mokushiroku,
        rating: "3.2/5",
        language: "Español",
        episodeNo: 146,
        readed: "275k",
        description: "un joven empobrecido que hace un contrato que fusiona su cuerpo con el de un demonio parecido a un perro llamado Pochita, otorgándole la capacidad de transformar partes de su cuerpo en motosierras",
    },
    jujutsukaisen: {
        id: 20,
        bookName: "Jujutsu \n Kaisen",
        bookCover: images.jujutsukaisen,
        rating: "3.2/5",
        language: "Español",
        episodeNo: 146,
        readed: "275k",
        description: "un joven empobrecido que hace un contrato que fusiona su cuerpo con el de un demonio parecido a un perro llamado Pochita, otorgándole la capacidad de transformar partes de su cuerpo en motosierras",
    },
    sonobisque: {
        id: 21,
        bookName: "Sonobisque",
        bookCover: images.sonobisque,
        rating: "3.2/5",
        language: "Español",
        episodeNo: 146,
        readed: "275k",
        description: "un joven empobrecido que hace un contrato que fusiona su cuerpo con el de un demonio parecido a un perro llamado Pochita, otorgándole la capacidad de transformar partes de su cuerpo en motosierras",
    },
    YofukashinoUta: {
        id: 22,
        bookName: "Yofukashino \n Uta",
        bookCover: images.YofukashinoUta,
        rating: "3.2/5",
        language: "Español",
        episodeNo: 146,
        readed: "275k",
        description: "un joven empobrecido que hace un contrato que fusiona su cuerpo con el de un demonio parecido a un perro llamado Pochita, otorgándole la capacidad de transformar partes de su cuerpo en motosierras",
    },
    vagabond: {
        id: 23,
        bookName: "Vagabond",
        bookCover: images.vagabond,
        rating: "3.2/5",
        language: "Español",
        episodeNo: 146,
        readed: "275k",
        description: "un joven empobrecido que hace un contrato que fusiona su cuerpo con el de un demonio parecido a un perro llamado Pochita, otorgándole la capacidad de transformar partes de su cuerpo en motosierras",
    },
    ShingekinoKyojin: {
        id: 24,
        bookName: "Shingekino \n Kyojin",
        bookCover: images.ShingekinoKyojin,
        rating: "3.2/5",
        language: "Español",
        episodeNo: 146,
        readed: "275k",
        description: "un joven empobrecido que hace un contrato que fusiona su cuerpo con el de un demonio parecido a un perro llamado Pochita, otorgándole la capacidad de transformar partes de su cuerpo en motosierras",
    },

}
